### ISSUE TITLE
Path mismatch exception when launching the tool

### ISSUE THREAD

**Issue by batuu19** [kianzarrin/LoadOrder#15]
When launching the tool I'm getting an exception and it won't launch. It could be because I have recently moved all my games to my new disk. So the game is installed now on F drive, it was on S before, but the path given in exception message doesn't even exist. I'm attaching log file.

System.Exception: Path mismatch! enabling/disabling may not work.
tool uses 'F:\Games\steamapps\workshop\content\255710'
game uses 'S:\Games\SteamLibrary\steamapps\workshop\content\255710'
	-- LoadOrderTool:end of inner stack trace --
   at CO.IO.DataLocation.ValidatePathMatch(CSCache csCache) in \CO\IO\DataLocation.cs:line 304
   at CO.IO.DataLocation..cctor() in \CO\IO\DataLocation.cs:line 145
   at LoadOrderTool.Program.Main() in \Program.cs:line 67

[LoadOrderTool.log](https://github.com/kianzarrin/LoadOrder/files/10002783/LoadOrderTool.log)

**Comment by MarkusDeutschmann** [comment]
For me a workaround was to replace all occurrences of the wrong paths 'F:\Games\Steam\steamapps\workshop\content\255710' in the CSCache.xml in directory'C:\Users\(username)\AppData\Local\Colossal Order\Cities_Skylines\LoadOrder' with the correct one 'F:\Games\Steam\SteamApps\workshop\content\255710'.

**Comment by kianzarrin** [comment]
if you hold ESC for several seconds the error eventually goes away. (fix will soon go to WS).

can you please check if you can enable/disable mods in LOT and the changes take effect in CS?

**Comment by kianzarrin** [comment]
I think this is mostly solved.
