### ISSUE TITLE
maybe bug?

### ISSUE THREAD

**Issue by indescribableQB** [kianzarrin/LoadOrder#16]
Sorry for the feedback here, I can't leave a message on steam because of the region. This problem seems to have existed for a long time, which is that when you exit the game and re-enter, the game language automatically returns to English. The Chinese Simplified I originally used will change to English when I enter the game, and even if I reset it back to Chinese Simplified, it will change back to English the next time I enter the game.

Here are the mods I'm using
![QQ截图20230109135121](https://user-images.githubusercontent.com/42056610/211247774-ff9eef59-1be2-4758-98b4-b379ea7af9cf.png)

**Comment by chameleon-tbn** [comment]
@indescribableQB please send us the Compatibility Report Logs zip File when you restart after you had changed the language

**Comment by kianzarrin** [comment]
how do you know its caused by LOM?
