### ISSUE TITLE
Assets are always loaded

### ISSUE THREAD

**Issue by meda22** [kianzarrin/LoadOrder#7]
Hi,

I am using Loading Order Mod V1.2.2-Beta right now and I am facing an issue when Assets get always loaded - even though I have excluded them and even checked "No Assets" in launch options.

I am also attaching logs.

Please can you check it out?
 
[LoadOrder.log](https://github.com/kianzarrin/LoadOrder/files/7961443/LoadOrder.log)
[LoadOrderIPatch.log](https://github.com/kianzarrin/LoadOrder/files/7961444/LoadOrderIPatch.log)
[LoadOrderTool.log](https://github.com/kianzarrin/LoadOrder/files/7961445/LoadOrderTool.log)
[output_log.txt](https://github.com/kianzarrin/LoadOrder/files/7961447/output_log.txt)

**Comment by meda22** [comment]
btw. I have tried it with alpha version too and same issue there...

**Comment by Leo512bit** [comment]
Have you got patch loader enabled?

**Comment by meda22** [comment]
> Have you got patch loader enabled?

I did... but I can make some more tests when I get bet to C:S

**Comment by kianzarrin** [comment]
from the log I can see no assets are excluded.
```
[Info] data path is C:\Users\Tomas\AppData\Local\Colossal Order\Cities_Skylines\LoadOrder
[Info] Excluded assets are: 
```
Do you see any excluded assets in `LoadOrderConfig.xml` located in the path above?

**Comment by meda22** [comment]
@kianzarrin thanks for answer! Actually, I don't have it any more because I had to go with clean install (rip hd) and I haven't been using LOM since then... So if you don't mind, I am going to close this issue - but if I start to use LOM again, I'll remember to check these config files should I run some issues again.
